CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email  VARCHAR(512)                            NOT NULL,
    name   VARCHAR(255)                            NOT NULL,
    rating FLOAT DEFAULT 0                         NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS locations
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    latitude  FLOAT                                   NOT NULL,
    longitude FLOAT                                   NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN DEFAULT FALSE                   NOT NULL,
    title  VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    annotation         VARCHAR(1024)                           NOT NULL,
    category_id        BIGINT                                  NOT NULL,
    confirmed_Requests BIGINT  DEFAULT 0,
    created_On         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    description        VARCHAR(1024)                           NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    initiator_id       BIGINT                                  NOT NULL,
    location_id        BIGINT                                  NOT NULL,
    paid               BOOLEAN DEFAULT FALSE                   NOT NULL,
    participant_Limit  BIGINT  DEFAULT 0                       NOT NULL,
    published_On       TIMESTAMP WITHOUT TIME ZONE,
    request_Moderation BOOLEAN DEFAULT TRUE,
    state              VARCHAR(20)                             NOT NULL,
    title              VARCHAR(512)                            NOT NULL,
    views              BIGINT  DEFAULT 0                       NOT NULL,
    compilation_id     BIGINT,
    rating             FLOAT   DEFAULT 0                       NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_event_category
        FOREIGN KEY (category_id) REFERENCES categories ON DELETE CASCADE,
    CONSTRAINT fk_event_user
        FOREIGN KEY (initiator_id) REFERENCES users ON DELETE CASCADE,
    CONSTRAINT fk_event_location
        FOREIGN KEY (location_id) REFERENCES locations ON DELETE CASCADE,
    CONSTRAINT fk_event_compilation
        FOREIGN KEY (compilation_id) REFERENCES compilations ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests
(
    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_id     BIGINT                                  NOT NULL,
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requester_id BIGINT                                  NOT NULL,
    status       VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_request_event
        FOREIGN KEY (event_id) REFERENCES events ON DELETE CASCADE,
    CONSTRAINT fk_request_user
        FOREIGN KEY (requester_id) REFERENCES users ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS event_likes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    liker_id   BIGINT                                  NOT NULL,
    event_id   BIGINT                                  NOT NULL,
    like_value FLOAT                                   NOT NULL,
    CONSTRAINT pk_event_likes PRIMARY KEY (id),
    CONSTRAINT fk_event_likes_user
        FOREIGN KEY (liker_id) REFERENCES users ON DELETE CASCADE,
    CONSTRAINT fk_event_likes_event
        FOREIGN KEY (event_id) REFERENCES events ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_likes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    liker_id   BIGINT                                  NOT NULL,
    rated_id   BIGINT                                  NOT NULL,
    like_value FLOAT                                   NOT NULL,
    CONSTRAINT pk_user_likes PRIMARY KEY (id),
    CONSTRAINT fk_user_likes_liker
        FOREIGN KEY (liker_id) REFERENCES users ON DELETE CASCADE,
    CONSTRAINT fk_user_likes_rated
        FOREIGN KEY (rated_id) REFERENCES users ON DELETE CASCADE
);