version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    volumes:
      - stats-db:/var/lib/postgresql/data
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmstats
      - POSTGRES_USER=ewmstats
      - POSTGRES_PASSWORD=ewmstats

  stats-server:
    build: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - ewm-db
    environment:
      - STATS_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewmstats
      - STATS_DATASOURCE_USERNAME=ewmstats
      - STATS_DATASOURCE_PASSWORD=ewmstats

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    volumes:
      - ewm-db:/var/lib/postgresql/data
    ports:
      - "6542:5432"
    depends_on:
      - stats-db
    environment:
      - POSTGRES_DB=ewmservice
      - POSTGRES_USER=ewmservice
      - POSTGRES_PASSWORD=ewmservice

  ewm-service:
    build: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
    environment:
      - EWM_STATS_SERVER_URL=http://stats-server:9090
      - SERVICE_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmservice
      - SERVICE_DATASOURCE_USERNAME=ewmservice
      - SERVICE_DATASOURCE_PASSWORD=ewmservice

volumes:
  ewm-db:
  stats-db:
